media_dir: media
root:
  subdirs:
    reuters:
      main:
        thread_id: 1532773363051028481
        title: Reuters is russian propaganda agency
      memes:
        thread_id: 1560518164001218562
        title: Reuters memese
      from_igor_sushko:
        thread_id: 1515750062839648256
        title: From Igor Sushko
  how_ukraine_dao_started:
    thread_id: 1525299116636622850
    title: How Ukraine DAO started
