name: Render

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'render/**'
      - 'common/**'
      - 'state/**'
      - 'twitter/**'
      - 'config.yml'
      - 'state.json'
      - 'go.*'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "render"
  cancel-in-progress: true

jobs:
  collect:
    permissions:
      id-token: write
      pages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote --recursive
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Collect tweets
        run: |
          go run ./render --config config.yml --state state.json --output_dir generated
      # TODO: fetch media
      - name: Commit updated state
        run: |
          cd generated
          git config user.name automation
          git config user.email github-actions@github.com
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Update generated files'
            git push
          fi
