name: Render

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "state"]
    paths:
      - 'render/**'
      - 'common/**'
      - 'state/**'
      - 'twitter/**'
      - 'config.yml'
      - 'state.json'
      - 'go.*'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "render"
  cancel-in-progress: true

jobs:
  render:
    environment: default
    permissions:
      id-token: write
      pages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch submodules
        run: |
          git submodule update --remote --init --recursive
          git submodule foreach --recursive git config --local http.https://github.com/.extraheader "$(git config --local http.https://github.com/.extraheader)"
          cd generated && git checkout generated
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Render
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          go run ./render --config config.yml --state stored-state/state.json --output_dir generated
      - name: Commit updated state
        run: |
          cd generated
          git config user.name automation
          git config user.email github-actions@github.com
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Update generated files'
            git push
          fi
